# Generated by Django 6.0.8 on 2026-08-04 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designacao', models.CharField(max_length=100, verbose_name='Designação (Ex: Item-001)')),
                ('nome_popular', models.CharField(max_length=150, verbose_name='Nome de Registro')),
                ('classe', models.CharField(choices=[('SAFE', 'Safe - Contenção Estável'), ('EUCLID', 'Euclid - Comportamento Imprevisível'), ('KETER', 'Keter - Ameaça de Fuga Ativa'), ('APOLLYON', 'Apollyon - Impossível de Conter')], default='EUCLID', max_length=20)),
                ('status', models.CharField(choices=[('CONTIDO', 'Contido com Sucesso'), ('BRECHA', 'Alerta de Brecha Crítica'), ('DESCONHECIDO', 'Paradeiro Desconhecido')], default='CONTIDO', max_length=20)),
                ('procedimento_contencao', models.TextField(verbose_name='Procedimentos Especiais de Contenção')),
                ('descricao', models.TextField(verbose_name='Descrição da Anomalia')),
                ('data_registro', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
