# Generated by Django 6.0.8 on 2026-08-04 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arquivos_scp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entidade',
            name='imagem_url',
            field=models.URLField(blank=True, max_length=1000, null=True, verbose_name='URL da Imagem de Contenção'),
        ),
        migrations.AlterField(
            model_name='entidade',
            name='designacao',
            field=models.CharField(max_length=100, verbose_name='Designação'),
        ),
        migrations.AlterField(
            model_name='entidade',
            name='procedimento_contencao',
            field=models.TextField(verbose_name='Procedimentos Especiais'),
        ),
    ]
